package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Manager;
import vn.com.vti.bus.entity.ManagerExample;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int deleteByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int insert(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int insertSelective(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    Manager selectByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int updateByExampleSelective(@Param("row") Manager row, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int updateByExample(@Param("row") Manager row, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int updateByPrimaryKeySelective(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.manager
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    int updateByPrimaryKey(Manager row);
}