package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.ReservationDetail;
import vn.com.vti.bus.entity.ReservationDetailExample;

public interface ReservationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    long countByExample(ReservationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int deleteByExample(ReservationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int deleteByPrimaryKey(Integer reservationDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int insert(ReservationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int insertSelective(ReservationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    List<ReservationDetail> selectByExample(ReservationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    ReservationDetail selectByPrimaryKey(Integer reservationDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int updateByExampleSelective(@Param("record") ReservationDetail record, @Param("example") ReservationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int updateByExample(@Param("record") ReservationDetail record, @Param("example") ReservationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int updateByPrimaryKeySelective(ReservationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    int updateByPrimaryKey(ReservationDetail record);
}