package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Route;
import vn.com.vti.bus.entity.RouteExample;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    long countByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int deleteByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int deleteByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int insert(Route row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int insertSelective(Route row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    List<Route> selectByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    Route selectByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int updateByExampleSelective(@Param("row") Route row, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int updateByExample(@Param("row") Route row, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int updateByPrimaryKeySelective(Route row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    int updateByPrimaryKey(Route row);
}