package vn.com.vti.bus.entity;

public class BusStop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_stop.bus_stop_id
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    private Integer busStopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_stop.bus_stop_name
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    private String busStopName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_stop.bus_stop_id
     *
     * @return the value of public.bus_stop.bus_stop_id
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    public Integer getBusStopId() {
        return busStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_stop.bus_stop_id
     *
     * @param busStopId the value for public.bus_stop.bus_stop_id
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    public void setBusStopId(Integer busStopId) {
        this.busStopId = busStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_stop.bus_stop_name
     *
     * @return the value of public.bus_stop.bus_stop_name
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    public String getBusStopName() {
        return busStopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_stop.bus_stop_name
     *
     * @param busStopName the value for public.bus_stop.bus_stop_name
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    public void setBusStopName(String busStopName) {
        this.busStopName = busStopName;
    }
}