package vn.com.vti.bus.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.manager_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.login_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.password
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.manager_id
     *
     * @return the value of public.manager.manager_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.manager_id
     *
     * @param managerId the value for public.manager.manager_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.login_id
     *
     * @return the value of public.manager.login_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.login_id
     *
     * @param loginId the value for public.manager.login_id
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.password
     *
     * @return the value of public.manager.password
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.password
     *
     * @param password the value for public.manager.password
     *
     * @mbg.generated Thu Jun 15 15:35:54 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }
}