package vn.com.vti.bus.entity;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.member_id
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.last_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.first_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.tel
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.email
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.password
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.member_id
     *
     * @return the value of public.member.member_id
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.member_id
     *
     * @param memberId the value for public.member.member_id
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.last_name
     *
     * @return the value of public.member.last_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.last_name
     *
     * @param lastName the value for public.member.last_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.first_name
     *
     * @return the value of public.member.first_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.first_name
     *
     * @param firstName the value for public.member.first_name
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.tel
     *
     * @return the value of public.member.tel
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.tel
     *
     * @param tel the value for public.member.tel
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.email
     *
     * @return the value of public.member.email
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.email
     *
     * @param email the value for public.member.email
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.password
     *
     * @return the value of public.member.password
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.password
     *
     * @param password the value for public.member.password
     *
     * @mbg.generated Fri May 26 15:38:35 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }
}