package vn.com.vti.bus.entity;

import java.util.ArrayList;
import java.util.List;

public class ReservationDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public ReservationDetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReservationDetailNoIsNull() {
            addCriterion("reservation_detail_no is null");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoIsNotNull() {
            addCriterion("reservation_detail_no is not null");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoEqualTo(Integer value) {
            addCriterion("reservation_detail_no =", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoNotEqualTo(Integer value) {
            addCriterion("reservation_detail_no <>", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoGreaterThan(Integer value) {
            addCriterion("reservation_detail_no >", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("reservation_detail_no >=", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoLessThan(Integer value) {
            addCriterion("reservation_detail_no <", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoLessThanOrEqualTo(Integer value) {
            addCriterion("reservation_detail_no <=", value, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoIn(List<Integer> values) {
            addCriterion("reservation_detail_no in", values, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoNotIn(List<Integer> values) {
            addCriterion("reservation_detail_no not in", values, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoBetween(Integer value1, Integer value2) {
            addCriterion("reservation_detail_no between", value1, value2, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationDetailNoNotBetween(Integer value1, Integer value2) {
            addCriterion("reservation_detail_no not between", value1, value2, "reservationDetailNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoIsNull() {
            addCriterion("reservation_no is null");
            return (Criteria) this;
        }

        public Criteria andReservationNoIsNotNull() {
            addCriterion("reservation_no is not null");
            return (Criteria) this;
        }

        public Criteria andReservationNoEqualTo(Integer value) {
            addCriterion("reservation_no =", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotEqualTo(Integer value) {
            addCriterion("reservation_no <>", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoGreaterThan(Integer value) {
            addCriterion("reservation_no >", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("reservation_no >=", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoLessThan(Integer value) {
            addCriterion("reservation_no <", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoLessThanOrEqualTo(Integer value) {
            addCriterion("reservation_no <=", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoIn(List<Integer> values) {
            addCriterion("reservation_no in", values, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotIn(List<Integer> values) {
            addCriterion("reservation_no not in", values, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoBetween(Integer value1, Integer value2) {
            addCriterion("reservation_no between", value1, value2, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotBetween(Integer value1, Integer value2) {
            addCriterion("reservation_no not between", value1, value2, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andSeatNameIsNull() {
            addCriterion("seat_name is null");
            return (Criteria) this;
        }

        public Criteria andSeatNameIsNotNull() {
            addCriterion("seat_name is not null");
            return (Criteria) this;
        }

        public Criteria andSeatNameEqualTo(String value) {
            addCriterion("seat_name =", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameNotEqualTo(String value) {
            addCriterion("seat_name <>", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameGreaterThan(String value) {
            addCriterion("seat_name >", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameGreaterThanOrEqualTo(String value) {
            addCriterion("seat_name >=", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameLessThan(String value) {
            addCriterion("seat_name <", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameLessThanOrEqualTo(String value) {
            addCriterion("seat_name <=", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameLike(String value) {
            addCriterion("seat_name like", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameNotLike(String value) {
            addCriterion("seat_name not like", value, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameIn(List<String> values) {
            addCriterion("seat_name in", values, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameNotIn(List<String> values) {
            addCriterion("seat_name not in", values, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameBetween(String value1, String value2) {
            addCriterion("seat_name between", value1, value2, "seatName");
            return (Criteria) this;
        }

        public Criteria andSeatNameNotBetween(String value1, String value2) {
            addCriterion("seat_name not between", value1, value2, "seatName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation_detail
     *
     * @mbg.generated do_not_delete_during_merge Sun May 21 23:11:40 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation_detail
     *
     * @mbg.generated Sun May 21 23:11:40 JST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}