package vn.com.vti.bus.entity;

import java.util.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservation.reservation_no
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    private Integer reservationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservation.reservation_datetime
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    private Date reservationDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservation.user_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservation.route_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    private Integer routeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservation.reservation_no
     *
     * @return the value of public.reservation.reservation_no
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Integer getReservationNo() {
        return reservationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservation.reservation_no
     *
     * @param reservationNo the value for public.reservation.reservation_no
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setReservationNo(Integer reservationNo) {
        this.reservationNo = reservationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservation.reservation_datetime
     *
     * @return the value of public.reservation.reservation_datetime
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Date getReservationDatetime() {
        return reservationDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservation.reservation_datetime
     *
     * @param reservationDatetime the value for public.reservation.reservation_datetime
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setReservationDatetime(Date reservationDatetime) {
        this.reservationDatetime = reservationDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservation.user_id
     *
     * @return the value of public.reservation.user_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservation.user_id
     *
     * @param userId the value for public.reservation.user_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservation.route_id
     *
     * @return the value of public.reservation.route_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservation.route_id
     *
     * @param routeId the value for public.reservation.route_id
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
}