package vn.com.vti.bus.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReservationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public ReservationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReservationNoIsNull() {
            addCriterion("reservation_no is null");
            return (Criteria) this;
        }

        public Criteria andReservationNoIsNotNull() {
            addCriterion("reservation_no is not null");
            return (Criteria) this;
        }

        public Criteria andReservationNoEqualTo(Integer value) {
            addCriterion("reservation_no =", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotEqualTo(Integer value) {
            addCriterion("reservation_no <>", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoGreaterThan(Integer value) {
            addCriterion("reservation_no >", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("reservation_no >=", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoLessThan(Integer value) {
            addCriterion("reservation_no <", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoLessThanOrEqualTo(Integer value) {
            addCriterion("reservation_no <=", value, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoIn(List<Integer> values) {
            addCriterion("reservation_no in", values, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotIn(List<Integer> values) {
            addCriterion("reservation_no not in", values, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoBetween(Integer value1, Integer value2) {
            addCriterion("reservation_no between", value1, value2, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationNoNotBetween(Integer value1, Integer value2) {
            addCriterion("reservation_no not between", value1, value2, "reservationNo");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeIsNull() {
            addCriterion("reservation_datetime is null");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeIsNotNull() {
            addCriterion("reservation_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeEqualTo(Date value) {
            addCriterion("reservation_datetime =", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeNotEqualTo(Date value) {
            addCriterion("reservation_datetime <>", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeGreaterThan(Date value) {
            addCriterion("reservation_datetime >", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reservation_datetime >=", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeLessThan(Date value) {
            addCriterion("reservation_datetime <", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("reservation_datetime <=", value, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeIn(List<Date> values) {
            addCriterion("reservation_datetime in", values, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeNotIn(List<Date> values) {
            addCriterion("reservation_datetime not in", values, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeBetween(Date value1, Date value2) {
            addCriterion("reservation_datetime between", value1, value2, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andReservationDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("reservation_datetime not between", value1, value2, "reservationDatetime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(Integer value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(Integer value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(Integer value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(Integer value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(Integer value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<Integer> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<Integer> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(Integer value1, Integer value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation
     *
     * @mbg.generated do_not_delete_during_merge Fri May 19 22:47:59 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.reservation
     *
     * @mbg.generated Fri May 19 22:47:59 JST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}