package vn.com.vti.bus.entity;

import java.util.Date;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.route_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.departure_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Integer departureBusStopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.departure_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private String departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.arrival_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Integer arrivalBusStopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.arrival_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private String arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.run_start_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Date runStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.run_end_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Date runEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.bus_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.route.price
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.route_id
     *
     * @return the value of public.route.route_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.route_id
     *
     * @param routeId the value for public.route.route_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.departure_bus_stop_id
     *
     * @return the value of public.route.departure_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Integer getDepartureBusStopId() {
        return departureBusStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.departure_bus_stop_id
     *
     * @param departureBusStopId the value for public.route.departure_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setDepartureBusStopId(Integer departureBusStopId) {
        this.departureBusStopId = departureBusStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.departure_time
     *
     * @return the value of public.route.departure_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.departure_time
     *
     * @param departureTime the value for public.route.departure_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.arrival_bus_stop_id
     *
     * @return the value of public.route.arrival_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Integer getArrivalBusStopId() {
        return arrivalBusStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.arrival_bus_stop_id
     *
     * @param arrivalBusStopId the value for public.route.arrival_bus_stop_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setArrivalBusStopId(Integer arrivalBusStopId) {
        this.arrivalBusStopId = arrivalBusStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.arrival_time
     *
     * @return the value of public.route.arrival_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.arrival_time
     *
     * @param arrivalTime the value for public.route.arrival_time
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.run_start_date
     *
     * @return the value of public.route.run_start_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Date getRunStartDate() {
        return runStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.run_start_date
     *
     * @param runStartDate the value for public.route.run_start_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setRunStartDate(Date runStartDate) {
        this.runStartDate = runStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.run_end_date
     *
     * @return the value of public.route.run_end_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Date getRunEndDate() {
        return runEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.run_end_date
     *
     * @param runEndDate the value for public.route.run_end_date
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setRunEndDate(Date runEndDate) {
        this.runEndDate = runEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.bus_id
     *
     * @return the value of public.route.bus_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.bus_id
     *
     * @param busId the value for public.route.bus_id
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.route.price
     *
     * @return the value of public.route.price
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.route.price
     *
     * @param price the value for public.route.price
     *
     * @mbg.generated Sat Jun 17 01:31:15 JST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}