package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Bus;
import vn.com.vti.bus.entity.BusExample;

public interface BusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    long countByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insert(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insertSelective(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    List<Bus> selectByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    Bus selectByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExampleSelective(@Param("record") Bus record, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExample(@Param("record") Bus record, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKeySelective(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKey(Bus record);
}