package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.BusStop;
import vn.com.vti.bus.entity.BusStopExample;

public interface BusStopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    long countByExample(BusStopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByExample(BusStopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByPrimaryKey(Integer busStopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insert(BusStop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insertSelective(BusStop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    List<BusStop> selectByExample(BusStopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    BusStop selectByPrimaryKey(Integer busStopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExampleSelective(@Param("record") BusStop record, @Param("example") BusStopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExample(@Param("record") BusStop record, @Param("example") BusStopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKeySelective(BusStop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_stop
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKey(BusStop record);
}