package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Reservation;
import vn.com.vti.bus.entity.ReservationExample;

public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int deleteByPrimaryKey(Integer reservationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    List<Reservation> selectByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    Reservation selectByPrimaryKey(Integer reservationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExampleSelective(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByExample(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservation
     *
     * @mbg.generated Sat May 20 09:09:10 JST 2023
     */
    int updateByPrimaryKey(Reservation record);
}